# consts
NO_RELATION_TAG = 'NR'
ALL_POSSIBLE_MODEL_LABELS = {'Kill', 'Located_In', 'Live_In', 'Work_For', 'OrgBased_In'}

# config
SPACY_MODEL_NAME = 'en_core_web_sm'
OUTPUT_TAG = 'Live_In'
MODEL_PREDICTED_LABELS = ALL_POSSIBLE_MODEL_LABELS # {OUTPUT_TAG}

CATBOOST_POSITIVE_CLASS_BOOST_FACTOR = 5
CATBOOST_LOGGING_LEVEL = 'Silent' # 'Info'
